### PR TITLE
css-three-column-layout | Rocky Truong

### PR DESCRIPTION
**Pull request by rocky-truong**
image

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Nice work so far!! The images have the rounded border cutting off the edge of the images, though. Please revise this to make the full image visible, as in the example. I suggest placing the image in a `div` container, and rounding the edges on that div, not the image itself.

**Comment by rocky-truong** [comment]
When I put the images in a div container, the border-radius: 50%; doesn't do anything to the images. Am I missing something?

**Comment by rocky-truong** [comment]
image

I added the div container for the images. I'm stuck on how to make the pictures fit inside the container properly.

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Yo dude!! I know you still have this in progress, just wanted to give you a review so it's clear there are still changes needed. If you have any questions on how to tackle this, make sure you reach out in Slack!

**Comment by rocky-truong** [comment]
image

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Rocky, your icons are not perfectly centered vertically in your image container. I recommend you look the the `align-items` section of the `css-flexbox` exercise for some ideas on how to fix this

**Comment by rocky-truong** [comment]
image

**Review by codingcodymiller — APPROVED** [review]
Nice job, dude!! 🎉

**Pull request merged**
